# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    ports:
      - '3307:3306'
    env_file:
      - .env.db
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  suitecrm:
    image: docker.io/library/suitecrm8-01
    ports:
      - '8081:8080'
      - '8443:8443'
    env_file:
      - .env.crm
    volumes:
      - 'suitecrm_data:/bitnami/suitecrm'
    depends_on:
      - mariadb
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6381:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:8
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'

volumes:
  mariadb_data:
    driver: local
  suitecrm_data:
    driver: local
  redis_data:
    driver: local
  elasticsearch_data:
    driver: local